apiVersion: apps/v1
kind: Deployment
metadata:
  name: theresg
spec:
  replicas: {{ .Values.workloads.theresg.replicaCount }}
  selector:
    matchLabels:
      app: theresg
  template:
    metadata:
      labels:
        app: theresg
    spec:
      containers:
        - name: theresg
          image: ghcr.io/gisc/theresg:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: LTA_BUDGET_DB_HOST
              value: "{{ .Values.postgres.host }}"
            - name: LTA_BUDGET_DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: LTA_BUDGET_DB_NAME
              value: "{{ .Values.postgres.databases.theresgquota }}"
            - name: LTA_BUDGET_DB_USER
              value: "{{ .Values.postgres.username }}"
            - name: LTA_BUDGET_DB_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: NUXT_DATAMALL_API_KEY
              value: "{{ .Values.olaresEnv.NUXT_DATAMALL_API_KEY }}"
            - name: NUXT_ONEMAP_EMAIL
              value: "{{ .Values.olaresEnv.NUXT_ONEMAP_EMAIL }}"
            - name: NUXT_ONEMAP_PASSWORD
              value: "{{ .Values.olaresEnv.NUXT_ONEMAP_PASSWORD }}"
---
apiVersion: v1
kind: Service
metadata:
  name: theresg
spec:
  selector:
    app: theresg
  ports:
    - port: 3000
      targetPort: 3000
